### ISSUE TITLE
Animations-Gestures longPress

### ISSUE THREAD

**Issue by qinzhe** [btrn/Swift#39]
```
@objc func longPress(_ send: UIGestureRecognizer) {
        if(send.state == .began) {
        UIView.animate(withDuration: 0.33, animations: { () -> Void in
            self.dieCenter = self.penguuinView.center
            self.penguuinView.center = CGPoint(x: self.penguuinView.center.x, y: self.view.frame.size.height)
        }, completion: { (finished: Bool) -> Void in self.longPressBack()
        })
        }
    }

**Comment by qinzhe** [comment]
`{

       @objc func longPress(_ send: UIGestureRecognizer) {
        if(send.state == .began) {
        UIView.animate(withDuration: 0.33, animations: { () -> Void in
            self.dieCenter = self.penguuinView.center
            self.penguuinView.center = CGPoint(x: self.penguuinView.center.x, y: self.view.frame.size.height)
        }, completion: { (finished: Bool) -> Void in self.longPressBack()
        })
        }
        }
    

`

**Comment by btrn** [comment]
Implemented. Thanks qinzhe.
